$(function(){function h(a){return n.A((new Date).getTime()-a.getTime())}function p(){var a;a=j(this);if(!a.data("timeago")){a.data("timeago",{b:n.b(a)});var c=j.trim(a.text());0<c.length&&a.i("title",c)}a=a.data("timeago");isNaN(a.b)||j(this).text(h(a.b));return this}$("#back-top").j();var k,d,f,m;$(".myem").append('<n uers="znvygb:uv@sybevnaorefvre.pbz" ery="absbyybj" gnetrg="_oynax">Rznvy</n>'.replace(/[a-zA-Z]/g,function(a){return String.fromCharCode(("Z">=a?90:122)>=(a=a.charCodeAt(0)+13)?a:a-
26)}));$("#myemb").append('<n uers="znvygb:uv@sybevnaorefvre.pbz" ery="absbyybj" gnetrg="_oynax">uv@sybevnaorefvre.pbz</n>'.replace(/[a-zA-Z]/g,function(a){return String.fromCharCode(("Z">=a?90:122)>=(a=a.charCodeAt(0)+13)?a:a-26)}));$("#contact, #followbtn, #close").Y("click",function(){if($("#contact-box").U("hidden"))return $("#contact").c("selected"),$(".global").c("contact-active"),$("#contact-box").u("slow").d("hidden"),history.pushState(null,"contact","contact"),!1;$("#contact-box").j("fast").c("hidden");
$("#contact").d("selected");$(".global").d("contact-active");history.back()});$(document).W(function(a){27===a.keyCode&&($("#contact-box").j("fast").c("hidden"),$("#contact").d("selected"),$(".global").d("contact-active"))});var g=new Date;k=g.getFullYear();d=g.getUTCMonth();f=g.getUTCDay();m=g.getUTCHours();g=g.getUTCMinutes();$("#yr").append(k);$("#exp").append(k-2002);10>g&&(g="0"+g);$("#time").append(m+":"+g);0<=d&&7>d&&0!=f&&6>f&&9<time&&18>time?(k="very busy",d="icon-minus-sign",f="red",m="48"):
0<=d&&7>d&&0!=f&&6>f&&9>=time&&18<=time?(k="busy",d="icon-warning-sign",f="orange",m="24"):0<=d&&7>d&&(0==f||6==f)&&9<time&&18>time?(k="busy",d="icon-warning-sign",f="orange",m="24"):(k="good",d="icon-ok-sign",f="green",m="12");$("#mstatusi").c(d+" "+f);$("#mstatus").append(k);$("#mdelay").append(m);$(window).scroll(function(){100<$(this).scrollTop()?$("#back-top").u():$("#back-top").T()});$(window).load(function(){$("#back-top").m();$("#back-top").click(function(){$(this).m();$("body,html").e({scrollTop:0},
1100);return!1})});var j=jQuery;j.a=function(a){return a instanceof Date?h(a):"string"===typeof a?h(j.a.parse(a)):h(j.a.b(a))};var n=j.a;j.extend(j.a,{h:{n:6E4,o:!1,L:{G:null,H:null,M:"ago",N:"from now",K:"Now",B:"A minute",C:"%d minutes",w:"An hour",z:"%d hours",r:"A day",s:"%d days",D:"A month",F:"%d months",O:"A year",P:"%d years",l:[]}},A:function(a){function c(b,c){return(j.V(b)?b(c,a):b).replace(/%d/i,e.l&&e.l[c]||c)}var e=this.h.L,d=e.G,f=e.M;this.h.o&&(0>a&&(d=e.H,f=e.N),a=Math.abs(a));var b=
a/1E3,h=b/60,k=h/60,g=k/24,m=g/365,b=45>b&&c(e.K,Math.round(b))||90>b&&c(e.B,1)||45>h&&c(e.C,Math.round(h))||90>h&&c(e.w,1)||24>k&&c(e.z,Math.round(k))||48>k&&c(e.r,1)||30>g&&c(e.s,Math.floor(g))||60>g&&c(e.D,1)||365>g&&c(e.F,Math.floor(g/30))||2>m&&c(e.O,1)||c(e.P,Math.floor(m));return j.trim([d,b,f].join(" "))},parse:function(a){a=j.trim(a);a=a.replace(/\.\d\d\d+/,"");a=a.replace(/-/,"/").replace(/-/,"/");a=a.replace(/T/," ").replace(/Z/," UTC");a=a.replace(/([\+\-]\d\d)\:?(\d\d)/," $1$2");return new Date(a)},
b:function(a){a="time"===j(a).get(0).tagName.toLowerCase()?j(a).i("datetime"):j(a).i("title");return n.parse(a)}});j.v.a=function(){var a=this;a.f(p);var c=n.h;0<c.n&&setInterval(function(){a.f(p)},c.n);return a};document.createElement("abbr");document.createElement("time");$.Q({url:"https://api.twitter.com/1/statuses/user_timeline.json?include_entities=false&include_rts=false&screen_name=xpressyoo&count=1",dataType:"jsonp",Z:function(a){var c=/([A-Za-z]+:\/\/[A-Za-z0-9-_]+\.[A-Za-z0-9-_:%&~\?\/.=]+)/g,
e=/[#]+([A-Za-z0-9-_]+)/g,d=/[@]+([A-Za-z0-9-_]+)/g;$.f(a.slice(0,1),function(a,b){b.text=b.text.replace(c,'<a target="_blank" title="Go to link" href="$1">$1</a>');b.text=b.text.replace(e,'<a target="_blank" title="More on this hashtag?" href="http://search.twitter.com/search?q=$1">#$1</a>');b.text=b.text.replace(d,'<a target="_blank" title="Who is this guy?" href="http://twitter.com/$1">@$1</a>');b.I='<a target="_blank" title="Retweet" href="http://twitter.com/intent/retweet?tweet_id='+b.k+'"><i class="icon-retweet"></i></a>';
b.J='<a target="_blank" title="Reply" href="http://twitter.com/intent/tweet?in_reply_to='+b.k+'"><i class="icon-share-alt"></i></a>';b.q=$.a($.trim(b.R));b.X=b.k.replace('"',"");$("#tweet").append(b.text+'<span class="btt"><span class="tweet-date">'+b.q+'</span><span class="retweet">'+b.I+"&nbsp; "+b.J+"</span></span>")})}})});var l=jQuery;
l.v.m=function(){var h;h=l.extend({g:"click",t:5E3},h);this.f(function(){function p(){k&&document.getElementById("elRaptorShriek").play();d.e({bottom:"0"},function(){l(this).e({bottom:"-130px"},100,function(){var f=l(this).position().left+400;l(this).S(300).e({right:f},2200,function(){d=l("#elRaptor").p({bottom:"-700px",right:"0"})})})})}l(this);var k=!0;l("body").append('<img id="elRaptor" class="mob" style="display: none" src="http://florianbersier.com/lib/raptor.png" />');k&&l("body").append('<audio id="elRaptorShriek" preload="auto"><source src="http://florianbersier.com/lib/raptor-sound.mp3" /><source src="http://florianbersier.com/lib/raptor-sound.ogg" /></audio>');
var d=l("#elRaptor").p({position:"fixed","z-index":"999999",bottom:"-700px",right:"0",display:"block"});"timer"==h.g?setTimeout(p,h.t):"click"!=h.g&&"konami-code"==h.g&&l(window)})};
